language: node_js
node_js:
- "8.6.0"
deploy:
  provider: heroku
  api_key:
    secure: "e09dc44d-4d13-4d1f-bde6-e140878fcd61"
  app:
    master: gobelins-tpleadtech-prod
    develop: gobelins-tpleadtech-staging